{
 "title": "Blackbox Exporter for dns and tcp probe",
 "description": "A dashboard that monitors the Blackbox-exporter.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{job=~\".*/blackbox/.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "dns Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_dns_additional_rrs{job=~\".*/blackbox/.*\"})"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=~\".*/blackbox/.*\"})"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "instance" },
  {
   "title": "dns lookup time seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_dns_lookup_time_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "dns duration seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_duration_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "probe_duration_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "dns duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_dns_duration_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dns phase percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_dns_duration_seconds{job=~\".*/blackbox/.*\", instance=\"$instance\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}