{
 "title": "Blackbox Exporter for http probe",
 "description": "A dashboard that monitors the Blackbox-exporter.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success{job=~\".*/blackbox/.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_http_version{job=~\".*/blackbox/.*\"})"
    }
   ]
  },
  {
   "title": "Probes Success Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(probe_success{job=~\".*/blackbox/.*\", instance=\"$instance\"} == 1) OR vector(0)) / count(probe_http_version{job=~\".*/blackbox/.*\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Probes SSL Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(probe_http_ssl{job=~\".*/blackbox/.*\", instance=\"$instance\"} == 1) / count(probe_http_version{job=~\".*/blackbox/.*\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=~\".*/blackbox/.*\"})"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "instance" },
  {
   "title": "Uptime %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\".*/blackbox/.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Latest Response Code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\".*/blackbox/.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{job=~\".*/blackbox/.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_tls_version_info{job=~\".*/blackbox/.*\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Redirects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_redirects{job=~\".*/blackbox/.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_http_version{job=~\".*/blackbox/.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP phase percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=~\".*/blackbox/.*\", instance=~\"$instance\"} - time()"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{job=~\".*/blackbox/.*\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}