# editor: haifengsss@163.com
# 2019/04/29
# update date: 2021/11/15

- name: link /data to /data1 dir
  file: 
    src: '/data1' 
    dest: '/data' 
    owner: 'root'
    group: 'root' 
    mode: "0777" 
    state: 'link'
  when:
    - '"/data1" in ansible_mounts | json_query("[*].mount")'
  tags:
    - create_data_soft_link
  ignore_errors: true

- name: create base dir
  file: 
    path: '{{es_install_dir}}' 
    state: directory 
    owner: root 
    group: root 
    mode: "0755"

- name: create es dir
  file:
    path: "{{ item }}"
    owner: "{{ es_run_user }}"
    group: "{{ es_run_user }}"
    mode: "0755"
    state: directory
  loop: '{{es_dirs}}'
    #- "{{es_conf_dir}}"
    #- "{{es_log_dir}}"
    #- "{{es_var_dir}}"
    ## es_data_dir 是一个列表
    #- "{{es_data_dir[0]}}"
  when:
    - item != es_base_dir
    - item | dirname != es_base_dir
