#- name: reload_nginx_service
- name: restart_nginx_service_by_systemd
  systemd: 
    name: '{{nginx_svc_name}}'
    state: reloaded
    daemon_reload: yes


- name: reload_nginx_service_by_upstart
  service: 
    name: '{{nginx_svc_name}}' 
    state: reloaded

# TODO: waiting delete
#- name: add to service list
#  shell:
#    cmd: systemctl daemon-reload
#- name: systemctl_daemon_reload
#  systemd:
#    daemon_reload: yes
