- name: copy nginx boot file
  template: 
    src: '{{ item.src }}' 
    dest: '{{ item.dest }}' 
    owner: 'root' 
    group: 'root' 
    mode: "0644" 
    backup: yes
  loop:
    - src: '{{nginx_boot_file}}'
      dest: '/usr/lib/systemd/system/{{nginx_svc_name}}.service'

- name: set nginx boot and starting up
  systemd:
    name: '{{nginx_svc_name}}'
    enabled: yes
    daemon_reload: yes
    state: started
