- name: restart_tomcat_by_systemd
  ansible.builtin.systemd: 
    name: '{{tomcat_svc_name}}'
    state: restarted
    daemon_reload: true

- name: restart_tomcat_by_supervisor
  ansible.builtin.systemd: 
    name: '{{tomcat_svc_name}}'
    state: restarted
    daemon_reload: true
