
- name: modify core arguments for docker
  sysctl: 
    name: '{{ item.name }}' 
    value: '{{ item.value }}' 
    reload: yes 
    state: present 
    sysctl_file: /etc/sysctl.d/27docker.conf 
    sysctl_set: yes
  loop:
  - name: net.bridge.bridge-nf-call-ip6tables 
    value: 1
  - name: net.bridge.bridge-nf-call-iptables 
    value: 1
  ignore_errors: true
