{
 "title": "traefik kubernets service",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": "label_values(traefik_service_open_connections, service)"
   },
   { "name": "percentiles", "query": "95,99" }
  ]
 },
 "panels": [
  {
   "title": "service open connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{service=\"$service\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "service request code rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"$service\"})[10m]) by (code, method)",
     "legendFormat": "{{ method }}-{{code}}"
    }
   ]
  },
  {
   "title": "service request latency by code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_service_request_duration_seconds_bucket{service=\"$service\"}[5m])) by (service, code, le)) >0",
     "legendFormat": "{{service}}-{{code}}"
    }
   ]
  }
 ]
}