{
 "title": "Traefik-kubernetes-281-custom",
 "description": "Traefik dashboard prometheus",
 "tags": [ "traefik" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "percentiles", "query": "95,99" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "group",
    "query": "label_values(traefik_config_last_reload_success, job)"
   },
   {
    "name": "instance",
    "query": "label_values(traefik_config_last_reload_success{job=~\"$group\"}, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(traefik_config_last_reload_success{job=~\"$group\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(traefik_config_last_reload_success{job=~\"$group\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Traefik instances",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{condition=\"true\",pod=~\"ingress-traefik.*\"})"
    }
   ]
  },
  {
   "title": "Global latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=~\"2..\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "Latency over 5 min"
    }
   ]
  },
  {
   "title": "Per node latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=~\"2..\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Entrypoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{job=~\"$group\", instance=~\"$instance\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.1\",code=\"200\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (job) + sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (job)) / 2 / sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  {
   "title": "Service total requests over 1min per entrypoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{job=~\"$group\", instance=~\"$instance\"}[1m])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{job=~\"$group\", instance=~\"$instance\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_request_duration_seconds_bucket{le=\"0.1\",code=\"200\",job=~\"$group\", instance=~\"$instance\"}[5m])) by (job) + sum(rate(traefik_service_request_duration_seconds_bucket{le=\"0.3\",code=\"200\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (job)) / 2 / sum(rate(traefik_service_request_duration_seconds_count{code=\"200\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  {
   "title": "Service total requests over 1min per service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=~\"$group\", instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Per Service latency $percentiles th perc over 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles , sum(rate(traefik_service_request_duration_seconds_bucket{code=~\"2..\",job=~\"$group\", instance=~\"$instance\"}[5m])) by (service, le)) >0",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "HTTP Codes stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status code 2xx over 5min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code=~\"2..\",job=~\"$group\", instance=~\"$instance\"}[5m])) by (method, code)",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Status code 5xx over 5min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code=~\"5..\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (method, code)",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Others statuses code over 5min",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code!~\"2..|5..\", job=~\"$group\", instance=~\"$instance\"}[5m])) by (method, code)",
       "legendFormat": "{{ method }} : {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traefik memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container=\"traefik\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Memory used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=\"traefik\",namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Requested memory"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{container=\"traefik\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Limit memory usage"
      }
     ]
    },
    {
     "title": "Traefik CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"traefik\", namespace=~\"$namespace\", pod=~\"$pod\"}[2m]))",
       "legendFormat": "Cpu used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=\"traefik\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Requested cpu"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container=\"traefik\", namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Limit cpu usage"
      }
     ]
    }
   ]
  }
 ]
}