# editor: haifengsss@163.com
# update date: 2023/09/18

- name: create logstash dir
  ansible.builtin.file: 
    path: "{{ item }}" 
    owner: "{{ logstash_run_user }}" 
    group: "{{ logstash_run_user }}" 
    mode: "0755" 
    state: "directory"
  loop:
    - "{{logstash_conf_dir}}"
    - "{{logstash_child_conf_dir}}"
    - "{{logstash_data_dir}}"
    - "{{logstash_log_dir}}"
    - "{{logstash_var_dir}}"
  when:
    - item.startswith(logstash_base_dir) == true
    - item is not none
    - item != ""

