
- name: mkdir base dir
  ansible.builtin.file: 
    path: '{{item}}' 
    state: directory 
    owner: root 
    group: root 
    mode: "0755"
  loop:
    - "{{app_base_dir}}"
    - "{{tomcat_install_dir}}"

- name: mkdir tomcat dir
  ansible.builtin.file: 
    path: '{{item}}' 
    state: directory 
    owner: '{{tomcat_run_user}}'
    group: '{{tomcat_run_group}}' 
    mode: "0755"
  loop:
    - "{{tomcat_log_dir}}"
  when: item is defined and item is not none

