{
 "title": "Jmx Dashboard(tomcat)",
 "description": "jmx exporter monitor",
 "tags": [ "jmx" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "APP_NAME",
    "query": {
     "query": "label_values(up{job=\"jmx-exporter\"}, app_kubernetes_io_name)"
    }
   },
   {
    "name": "instance",
    "label": "POD_IP",
    "query": {
     "query": "label_values(up{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "java_lang_operatingsystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "up",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "java_lang_runtime_uptime",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_runtime_uptime{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"} / 1000"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "java_lang_runtime_starttime",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_runtime_starttime{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "description": "java_lang_operatingsystem_openfiledescriptorcount",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "gauge",
   "description": "java_lang_operatingsystem_systemcpuload",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_systemcpuload{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "CPU Process Load(1m avg)",
   "type": "gauge",
   "description": "java_lang_operatingsystem_processcpuload",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_operatingsystem_processcpuload{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "stat",
   "description": "java_lang_operatingsystem_systemloadaverage",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemloadaverage{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "java_lang_operatingsystem_availableprocessors",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_availableprocessors{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "java_lang_garbagecollector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "GC count",
   "type": "graph",
   "description": "java_lang_garbagecollector_collectioncount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(java_lang_garbagecollector_collectioncount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "description": "java_lang_garbagecollector_collectiontime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(java_lang_garbagecollector_collectiontime{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  { "title": "java_lang_memorypool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "description": "java_lang_memorypool_usage_used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_usage_used{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Memory Pool Committed",
   "type": "graph",
   "description": "java_lang_memorypool_usage_committed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memorypool_usage_committed{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  { "title": "java_lang_memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Heap /NonHeap Used",
   "type": "graph",
   "description": "java_lang_memory_heapmemoryusage_used /  java_lang_memory_nonheapmemoryusage_used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "HeapMemory"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_used{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "NonHeapMemory"
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap Committed",
   "type": "graph",
   "description": "java_lang_memory_heapmemoryusage_committed /  java_lang_memory_nonheapmemoryusage_committed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_committed{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "HeapMemory"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_committed{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "NonHeapMemory"
    }
   ]
  },
  { "title": "java_lang_threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Threads Used",
   "type": "graph",
   "description": "java_lang_threading_threadcount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_threading_threadcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "java_lang_threading_daemonthreadcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  { "title": "java_lang_classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Class Loaded / Unloaded",
   "type": "graph",
   "description": "java_lang_classloading_loadedclasscount / java_lang_classloading_unloadedclasscount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_classloading_loadedclasscount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "java_lang_classloading_unloadedclasscount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  { "title": "Catalina", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Catalina Request Processor bytes",
   "type": "graph",
   "description": "catalina_globalrequestprocessor_bytesreceived /  catalina_globalrequestprocessor_bytessent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(catalina_globalrequestprocessor_bytesreceived{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}} recv"
    },
    {
     "expr": "increase(catalina_globalrequestprocessor_bytessent{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  {
   "title": "Catalina Request Processor requests",
   "type": "graph",
   "description": "catalina_globalrequestprocessor_requestcount  /   catalina_globalrequestprocessor_errorcount",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(catalina_globalrequestprocessor_requestcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}} count"
    },
    {
     "expr": "increase(catalina_globalrequestprocessor_errorcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{name}} error"
    }
   ]
  },
  {
   "title": "Catalina Request Processing Time",
   "type": "graph",
   "description": "catalina_globalrequestprocessor_processingtime",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(catalina_globalrequestprocessor_processingtime{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m]) / increase(catalina_globalrequestprocessor_requestcount{job=\"jmx-monitor\", teddy_app=\"$app\", instance=~\"$instance\"}[1m])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Catalina ThreadPool",
   "type": "graph",
   "description": "catalina_readpool_connectioncount /  catalina_threadpool_currentthreadsbusy  /  catalina_threadpool_connectioncount   /   catalina_threadpool_keepalivecount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_currentthreadcount{job=\"jmx-exporter\", instance=~\"$instance\"}",
     "legendFormat": "current: {{name}}"
    },
    {
     "expr": "catalina_threadpool_currentthreadsbusy{job=\"jmx-exporter\", instance=~\"$instance\"}",
     "legendFormat": "current busy: {{name}}"
    },
    {
     "expr": "catalina_threadpool_connectioncount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "connection: {{name}}"
    },
    {
     "expr": "catalina_threadpool_keepalivecount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "keepAlive: {{name}}"
    }
   ]
  },
  {
   "title": "Max Threads",
   "type": "graph",
   "description": "catalina_threadpool_maxthreads",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_maxthreads{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Min Spare Threads",
   "type": "graph",
   "description": "catalina_threadpool_minsparethreads",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_minsparethreads{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Accept Count",
   "type": "graph",
   "description": "catalina_threadpool_acceptcount",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_acceptcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Poller Thread Count",
   "type": "graph",
   "description": "catalina_threadpool_pollerthreadcount",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_threadpool_pollerthreadcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count",
   "type": "graph",
   "description": "catalina_servlet_requestcount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(catalina_servlet_requestcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet error count",
   "type": "graph",
   "description": "catalina_servlet_errorcount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(catalina_servlet_errorcount{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlets average processing time per request",
   "type": "graph",
   "description": "catalina_servlet_processingtime  /  catalina_servlet_requestcount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(catalina_servlet_processingtime{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m]) / increase(catalina_servlet_requestcount{job=\"jmx-monitor\", teddy_app=\"$app\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Catalina Manager Sessions",
   "type": "graph",
   "description": "catalina_manager_expiredsessions  /   catalina_manager_rejectedsessions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(catalina_manager_expiredsessions{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(increase(catalina_manager_rejectedsessions{job=\"jmx-exporter\", app_kubernetes_io_name=\"$app\", instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "rejected"
    }
   ]
  }
 ]
}